import mysql.connector
import json
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from backend/.env
env_path = Path(__file__).parent.parent / 'backend' / '.env'
load_dotenv(dotenv_path=env_path)

DB_CONFIG = {
    'host': os.getenv('DATABASE_URL', '').split('@')[-1].split(':')[0] or 'localhost',
    'user': os.getenv('DATABASE_URL', '').split('://')[1].split(':')[0] if '://' in os.getenv('DATABASE_URL', '') else 'root',
    'password': os.getenv('DATABASE_URL', '').split(':')[2].split('@')[0] if ':' in os.getenv('DATABASE_URL', '') else '1001',
    'database': os.getenv('DATABASE_URL', '').split('/')[-1].split('?')[0] or 'girl_pick_db',
    'port': 3306
}

# Manual override if env parsing fails or is different for local
DB_CONFIG['password'] = '1001'
DB_CONFIG['database'] = 'girl_pick_db'

OUTPUT_FILE = Path(__file__).parent / 'sync_cdn_to_vps.sql'

def export_cdn_sql():
    print(f"🔍 Đang kết nối tới Database Local: {DB_CONFIG['database']}...")
    try:
        connection = mysql.connector.connect(**DB_CONFIG)
        cursor = connection.cursor(dictionary=True)
        
        # Lấy toàn bộ thông tin bảng girls cho những bản ghi đã migrate
        query = "SELECT * FROM girls WHERE images LIKE '%girlpick.b-cdn.net%'"
        cursor.execute(query)
        rows = cursor.fetchall()
        
        if not rows:
            print("❌ Không tìm thấy dữ liệu nào có link CDN ở Local.")
            return

        columns = [i[0] for i in cursor.description]
        print(f"📦 Tìm thấy {len(rows)} bản ghi. Đang tạo file SQL đồng bộ TOÀN BỘ cột...")
        
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write("-- SQL Full Sync Script generated for girls table\n")
            f.write("-- Generated by Antigravity\n\n")
            f.write("SET FOREIGN_KEY_CHECKS = 0;\n")
            f.write("USE girl_pick_db;\n\n")
            
            for row in rows:
                # Sử dụng REPLACE INTO để ghi đè toàn bộ thông tin nếu ID đã tồn tại
                vals = []
                for col in columns:
                    val = row[col]
                    if val is None:
                        vals.append("NULL")
                    elif isinstance(val, (int, float)):
                        vals.append(str(val))
                    elif isinstance(val, (dict, list)): # Cho trường JSON images
                        json_val = json.dumps(val, ensure_ascii=False).replace("'", "''")
                        vals.append(f"'{json_val}'")
                    else:
                        # Escape single quotes in strings
                        str_val = str(val).replace("'", "''")
                        vals.append(f"'{str_val}'")
                
                col_names = ", ".join([f"`{c}`" for c in columns])
                val_placeholders = ", ".join(vals)
                sql = f"REPLACE INTO girls ({col_names}) VALUES ({val_placeholders});\n"
                f.write(sql)
            
            f.write("\nSET FOREIGN_KEY_CHECKS = 1;\n")
                
        print(f"✅ Thành công! Đã tạo file: {OUTPUT_FILE.absolute()}")
        print(f"👉 Chú ý: Lệnh REPLACE INTO sẽ ghi đè TOÀN BỘ dữ liệu của các cô gái này trên VPS bằng dữ liệu Local.")
                
        print(f"✅ Thành công! Đã tạo file: {OUTPUT_FILE.absolute()}")
        print(f"👉 Hướng dẫn: Bạn chỉ cần copy nội dung file này và chạy (Execute) trên database VPS là xong.")
        
        cursor.close()
        connection.close()
        
    except Exception as e:
        print(f"❌ Lỗi: {e}")

if __name__ == "__main__":
    export_cdn_sql()
